# Generated by Django 3.2 on 2021-05-18 10:15

import chatroom.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=256)),
                ('room_uid', models.CharField(default=chatroom.utils.uid_gen, editable=False, max_length=36)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
