# Generated by Django 3.2 on 2021-05-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0003_remove_privateroom_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privateroom',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
